### ISSUE TITLE
Version 1.0.6 broke testing on Windows and macOS

### ISSUE THREAD

**Issue by ocefpaf** [s-weigand/setup-conda#125]
Our setup in in https://github.com/ioos/erddapy/commit/9232d714ee158c9840956a6e2d5bb5a98557322c works with version 1.0.5 but not 1.0.6. See https://github.com/ioos/erddapy/pull/193 where we had to pin the to previous version version to make it work.

Note that, by using `activate-conda: true` we could get 1.0.6 to work on Linux only. However, my understanding is that we don't need to activate the base env b/c we are activating the TEST env later.

Happy to provide any with further details if needed. Also, thanks for the awesome GHA! Very useful!!

**Comment by s-weigand** [comment]
Thanks for the report.
It looks like that with `v1.0.6` on Linux for some reason `/usr/bin` is too early in the `PATH` and thus the system `pip` is used which requires sudo rights and thus fails to install your package.

- `v1.0.5`
  ```
  PATH: /usr/share/miniconda/bin:/usr/share/miniconda/envs/TEST/bin:/usr/share/miniconda/condabin:/usr/bin:/usr/share/miniconda/bin:/usr/share/miniconda:/home/linuxbrew/.linuxbrew/bin:
  ```
- `v1.0.6`
  ```
  PATH: /usr/share/miniconda/bin:/usr/bin:/usr/share/miniconda/envs/TEST/bin:/usr/share/miniconda/condabin:/usr/share/miniconda:/home/linuxbrew/.linuxbrew/bin
  ```

I will add a test with `bash -l {0}` and try to come up with a fix asap.

**Comment by s-weigand** [comment]
@all-contributors please add @ocefpaf for bug

**Comment by s-weigand** [comment]
Ok it looks like adding the env vars from the activation script (`conda shell.<shell_name> activate <env_name>`) broke the usage of `source activate <env_name>`.

@ocefpaf Would you be so kind and confirm that using `s-weigand/setup-conda@fix-env-activation` resolves your problem? 🤞

**Comment by s-weigand** [comment]
@ocefpaf Sorry the `fix-env-activation` didn't contain the transpiled code in `dist/index.js` that is why [that run](https://github.com/ioos/erddapy/runs/2980276077?check_suite_focus=true) failed.
Could you try `s-weigand/setup-conda@fix-env-activation-dist`?

**Comment by ocefpaf** [comment]
> Could you try `s-weigand/setup-conda@fix-env-activation-dist`?

Ah! I though it was copy-n-pasta from my side :smile: 

Done and it worked!

**Comment by s-weigand** [comment]
The problem with automating everything, is that you can easily forget something when it isn't the used workflow 😅 

`dist/index.js` is bundled code used by the action, but not to have bundle conflicts it is in the `.gitignore`.
Since the CI first bundels the code and the tests use the bundle artifact from the previous job, I forgot that you can't use the branch directly to test it 😅
