### ISSUE TITLE
bash: /tmp/2021029-2444-1687tb4.wkq9.sh: No such file or directory

### ISSUE THREAD

**Issue by UnHumbleBen** [s-weigand/setup-conda#72]
**Describe the bug**
Workflow fails and due to file not found error:
```
Run s-weigand/setup-conda@v1
  with:
    activate-conda: true
    update-conda: false
    python-version: default
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
which python
stdout /opt/hostedtoolcache/Python/3.7.9/x64/bin/python

/opt/hostedtoolcache/Python/3.7.9/x64/bin/python
Adding conda path to path: /usr/share/miniconda
Activating conda base
bash /tmp/2021029-2444-c6jfmq.81qsc.sh
Activating conda base
bash /tmp/2021029-2444-1687tb4.wkq9.sh
bash: /tmp/2021029-2444-1687tb4.wkq9.sh: No such file or directory
Error: The process 'bash' failed with exit code 127
```

**To Reproduce**

Not sure how to reproduce, but here is [the run that caused this error](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/164/checks?check_run_id=1791956300)

**Expected behavior**

Setup Conda as expected

**Comment by s-weigand** [comment]
Thanks for the bug report.
Did this only happen once or does it happen on regular basis?
Right now this looks like a random hiccup on the action runner to me.

**Comment by UnHumbleBen** [comment]
Only once. Any idea how a hiccup could happen with the action runner?

**Comment by s-weigand** [comment]
Well, that kinda is the problem with the "hiccups", they scarcely happen with no apparent reason e.g. I saw runners fail at checkout of a repo. And if you just run the job again all works fine.
My best guess is that there might be some kind of racing condition with the load balancer and the hardware resources from time to time, but who knows ¯\_(ツ)_/¯
When a CI run/step fails for a tome a nonsensical reason, I just restart it sometime later and when the error persists I start investigating.

Anyway I will close this issue for now, but feel free to post again if this comes up more often.
